# Generated by Django 5.0.2 on 2024-02-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('emp_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_Name', models.CharField(max_length=100)),
                ('emp_Dept', models.CharField(max_length=100)),
                ('emp_location', models.CharField(max_length=100)),
                ('emp_country', models.CharField(max_length=100)),
            ],
        ),
    ]
